spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: file:///Users/olexiy/Documents/MyProjects/spring_cloud_sample/in28minutes/git-localconfig-repo
server:
  port: ${port:8888}
